appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: l4fmCBE1dZEupFEnNNWu7gzjQ1+iJfijm1qhL6Go9oiz9IrAUY3auaDHAbI43z2ECF2YaDUNNuWMH8cR4aPCT7G+oLIBvRQ1BAnwW9D1L7t/Dyi1NS+rXuwXnBwDOX+1yFhfSUgDly6/jH1lCxIcBNZZMHk7tJrOuE3zuFTB8YYDVWrehMyHjZD+txshPz26SkK8w9LPnnz77wH7rs8kzIrMSW0XfTVVxrvHwZFyfHBUGJh+pRS/q0smIn9N5a70zuHgdpL2Xp+MkHD/PqlJOdtxnz88ngvPwGdrZpbZj8eftiPWCaToeKD7bhQPIDxbTF5Q+1NcflnJChspaNnU/fivPi1lTQF6jYBWRuv8vsEIFfIOnz9TjxsIKu0PvHe+TjpDJ8UayDMhkzPYhWUpQU4FHYg9m0vwGjsW0o1UaLqCooGIWMlzXElK7bkKaCjQ3Tih8wJ7EXY/vCOOZCfG9p8+czg+IOfv70Ttew4ztlgIgx7IRSgFY2uxSyW1IUZT4I2ITXV1bKebgxAU1g1dyaOf06ynpIBFgroaK3ASrHMZV5y1HfSg2jAIXtnPyjeJbhA+2OwYZmd6gJpSDWOBmh+uU0F0ZDB6QF9rBxCr7ok5usUDecUP1wYbWlWH66AewLr/3ZrLC0W59U0PwlqE1OJH1+4RaYMMOmMQOzcNJUI=}
bot:
  automerge: true
